$       ENV     = F$ENVIRONMENT("PROCEDURE")
$       HOME    = F$PARSE("Z.Z;",ENV,,,) - "Z.Z;"
$	NODE	= F$GETSYI("NODENAME")
$
$	RUN	SYS$SYSTEM:LOGINOUT.EXE -
	/DETACH - 
	/PROCESS_NAME="SPOP3-SRV" -
	/INPUT='HOME'SPOP3_SRV$START.COM -
	/OUTPUT='HOME'SPOP3_SRV-'NODE'.LOG -
!	/OUTPUT=_NLA0: -
	/ERROR='HOME'SPOP3_SRV-'NODE'.ERR -
	/UIC=SYSTEM -
	/AUTHORIZE -
	/DUMP
