$	!
$	SET OUTPUT_RATE = 0:00:05
$	SET VERIFY
$	SET PROTECTION=W /DEFAULT
$
$	ENV     = F$ENVIRONMENT("PROCEDURE")
$	HOME    = F$PARSE("Z.Z;", ENV,,,) - "Z.Z;"
$	NODE	= F$GETSYI("NODENAME")
$
$LOOP:
$	@'HOME'SPOP3_SRV$LOGICALS.COM
$	!
$	SET NOON
$
$	RUN/NODEBUG	'HOME'SPOP3_SRV
$	STATUS = $STATUS
$
$	IF STATUS.EQ.1	THEN $EXIT
$
$	!
$	 MAIL    _NLA0:  LAISHEV /NOSIG/NOSELF/NOEDIT -
		/SUBJ="%SPOP3-S-STOP, SPOP3 Server stopped;''F$MESSAGE(STATUS)'"
$	WAIT	00:00:30
$	GOTO	LOOP
